-- defaults.lua
-- Centralized defaults for physcomod

function ApplyDefaultSettings()
    -- Debug: indicate defaults applied (helpful for playtesting)
    if DebugPrint then pcall(DebugPrint, "ApplyDefaultSettings: setting canonical defaults") end
    -- Feature toggles defaults
    SetBool("savegame.mod.combined.Tog_FPSC", false)
    SetBool("savegame.mod.combined.Tog_DUST", false)
    SetBool("savegame.mod.combined.Tog_CRUMBLE", true)
    SetBool("savegame.mod.combined.Tog_RUMBLE", false)
    SetBool("savegame.mod.combined.Tog_FORCE", false)
    SetBool("savegame.mod.combined.Tog_FIRE", false)
    SetBool("savegame.mod.combined.Tog_VIOLENCE", false)
    SetBool("savegame.mod.combined.Tog_DAMSTAT", false)
    SetBool("savegame.mod.combined.Tog_JOINTS", false)
    SetBool("savegame.mod.combined.Tog_IMPACT", true)
    SetBool("savegame.mod.combined.Tog_MASS", true)

    -- IBSIT core defaults
    SetInt("savegame.mod.combined.ibsit_momentum", 20)
    SetInt("savegame.mod.combined.ibsit_dust_amt", 10)
    SetInt("savegame.mod.combined.ibsit_wood_size", 100)
    SetInt("savegame.mod.combined.ibsit_stone_size", 100)
    SetInt("savegame.mod.combined.ibsit_metal_size", 100)
    SetBool("savegame.mod.combined.ibsit_haptic", false)
    SetBool("savegame.mod.combined.ibsit_sounds", false)
    SetBool("savegame.mod.combined.ibsit_particles", true)
    SetBool("savegame.mod.combined.ibsit_vehicle", false)
    SetBool("savegame.mod.combined.ibsit_joint", false)
    SetBool("savegame.mod.combined.ibsit_protection", false)
    SetFloat("savegame.mod.combined.ibsit_volume", 1.0)
    SetInt("savegame.mod.combined.ibsit_particle_quality", 1)

    -- Gravity collapse defaults
    SetBool("savegame.mod.combined.ibsit_gravity_collapse", true)
    SetFloat("savegame.mod.combined.ibsit_collapse_threshold", 0.7)
    SetFloat("savegame.mod.combined.ibsit_gravity_force", 9.81)
    SetInt("savegame.mod.combined.gravitycollapse_sample_count", 24)
    SetFloat("savegame.mod.combined.gravitycollapse_check_interval", 0.6)
    SetInt("savegame.mod.combined.gravitycollapse_min_mass", 50)
    SetBool("savegame.mod.combined.gravitycollapse_debug", false)
    SetBool("savegame.mod.combined.gravitycollapse_joint_credit", true)
    SetInt("savegame.mod.combined.gravitycollapse_joint_depth", 6)
    SetInt("savegame.mod.combined.gravitycollapse_joint_mass_threshold", 100)
    SetInt("savegame.mod.combined.gravitycollapse_min_samples", 6)
    SetInt("savegame.mod.combined.gravitycollapse_max_samples", 64)
    SetFloat("savegame.mod.combined.gravitycollapse_cache_grid", 0.25)
    SetFloat("savegame.mod.combined.gravitycollapse_cache_ttl", 1.0)
    SetBool("savegame.mod.combined.gravitycollapse_cache_invalidate_on_check", false)
    SetFloat("savegame.mod.combined.gravitycollapse_cache_invalidate_pad", 0.05)
    SetBool("savegame.mod.combined.gravitycollapse_profiler", true)
    SetFloat("savegame.mod.combined.gravitycollapse_profile_interval", 1.0)

    -- FPS Control Section
    SetBool("savegame.mod.combined.FPS_DynLights", true)
    SetBool("savegame.mod.combined.Tog_SDF", true)
    SetBool("savegame.mod.combined.Tog_LFF", false)
    SetBool("savegame.mod.combined.Tog_DBF", false)
    SetInt("savegame.mod.combined.FPS_SDF", 7)
    SetInt("savegame.mod.combined.FPS_LFF", 0)
    SetInt("savegame.mod.combined.FPS_DBF", 0)
    SetInt("savegame.mod.combined.FPS_DBF_size", 35)
    SetBool("savegame.mod.combined.FPS_DBF_FPSB", true)
    SetInt("savegame.mod.combined.FPS_SDF_agg", 3)
    SetInt("savegame.mod.combined.FPS_LFF_agg", 1)
    SetInt("savegame.mod.combined.FPS_DBF_agg", 1)
    SetInt("savegame.mod.combined.FPS_Targ", 30)
    SetInt("savegame.mod.combined.FPS_Agg", 1)
    SetBool("savegame.mod.combined.FPS_GLOB_agg", false)
    SetInt("savegame.mod.combined.FPS_GLOB_aggfac", 0)

    -- Dust Control Section
    SetInt("savegame.mod.combined.dust_amt", 50)
    SetBool("savegame.mod.combined.dust_DustMeth", false)
    SetInt("savegame.mod.combined.dust_size", 100)
    SetInt("savegame.mod.combined.dust_sizernd", 50)
    SetInt("savegame.mod.combined.dust_MsBsSz", 50)
    SetInt("savegame.mod.combined.dust_grav", 35)
    SetInt("savegame.mod.combined.dust_drag", 15)
    SetInt("savegame.mod.combined.dust_life", 16)
    SetInt("savegame.mod.combined.dust_lifernd", 10)
    SetInt("savegame.mod.combined.dust_MsBsLf", 20)
    SetInt("savegame.mod.combined.dust_minMass", 3)
    SetInt("savegame.mod.combined.dust_minSpeed", 3)
    SetInt("savegame.mod.combined.dust_startsize", 10)
    SetInt("savegame.mod.combined.dust_fader", 5)

    -- Crumbling Section
    SetBool("savegame.mod.combined.tog_crum", true)
    SetInt("savegame.mod.combined.tog_crum_MODE", 0)
    SetInt("savegame.mod.combined.tog_crum_Source", 0)
    SetInt("savegame.mod.combined.crum_DMGLight", 50)
    SetInt("savegame.mod.combined.crum_DMGMed", 50)
    SetInt("savegame.mod.combined.crum_DMGHeavy", 50)
    SetInt("savegame.mod.combined.crum_spd", 2)
    SetFloat("savegame.mod.combined.crum_spdRND", 0.01)
    SetInt("savegame.mod.combined.crum_dist", 8)
    SetBool("savegame.mod.combined.vehicles_crumble", false)
    SetInt("savegame.mod.combined.crum_HoleControl", 4)
    SetFloat("savegame.mod.combined.crum_BreakTime", 2.5)
    SetInt("savegame.mod.combined.crum_distFromPlyr", 40)
    SetInt("savegame.mod.combined.crum_MinMass", 1)
    SetInt("savegame.mod.combined.crum_MaxMass", 1000)
    SetFloat("savegame.mod.combined.crum_MinSpd", 0.0025)
    SetFloat("savegame.mod.combined.crum_MaxSpd", 8)

    -- Explosions Section
    SetFloat("savegame.mod.combined.xplo_szBase", 0.35)
    SetFloat("savegame.mod.combined.xplo_szRND", 0.15)
    SetFloat("savegame.mod.combined.xplo_szMBV", 0.15)
    SetInt("savegame.mod.combined.xplo_chance", 4)
    SetInt("savegame.mod.combined.xplo_HoleControl", 4)
    SetFloat("savegame.mod.combined.xplo_BreakTime", 2.5)
    SetInt("savegame.mod.combined.xplo_distFromPlyr", 40)
    SetInt("savegame.mod.combined.xplo_MinMass", 1)
    SetInt("savegame.mod.combined.xplo_MaxMass", 10000)
    SetFloat("savegame.mod.combined.xplo_MinSpd", 0.0025)
    SetFloat("savegame.mod.combined.xplo_MaxSpd", 8)
    SetInt("savegame.mod.combined.xplo_SmokeAMT", 2)
    SetInt("savegame.mod.combined.xplo_LifeAMT", 2)
    SetInt("savegame.mod.combined.xplo_Pressure", 4)
    SetInt("savegame.mod.combined.xplo_mode", 1)

    -- Force and Wind Section
    SetInt("savegame.mod.combined.force_method", 1)
    SetFloat("savegame.mod.combined.force_gamecontrols", 0.35)
    SetFloat("savegame.mod.combined.force_radius", 0.35)
    SetFloat("savegame.mod.combined.force_maxmass", 0.35)
    SetFloat("savegame.mod.combined.force_minmass", 0.35)
    SetFloat("savegame.mod.combined.force_strength", 0.35)
    SetFloat("savegame.mod.combined.force_boost", 0.35)
    SetBool("savegame.mod.combined.force_EdgeFade", true)
    SetBool("savegame.mod.combined.force_START_ON", false)
    SetBool("savegame.mod.combined.force_ENABLE_CONTROLS", false)
    SetBool("savegame.mod.combined.force_Showcross", false)
    SetBool("savegame.mod.combined.force_CONTROL_TIPS", false)
    SetFloat("savegame.mod.combined.force_cycle", 0.35)
    SetFloat("savegame.mod.combined.force_largemass_accellerator", 0.35)
    SetFloat("savegame.mod.combined.force_upforce", 0.35)
    SetFloat("savegame.mod.combined.force_effect_on_player", 0)
    SetFloat("savegame.mod.combined.force_rotational", 0)
    SetFloat("savegame.mod.combined.force_warmup", 1)

    -- Fire Section
    SetInt("savegame.mod.combined.fyr_mode", 1)
    SetInt("savegame.mod.combined.fyr_maxrad", 15)
    SetInt("savegame.mod.combined.fyr_minrad", 4)
    SetInt("savegame.mod.combined.fyr_chance", 1)
    SetInt("savegame.mod.combined.fyr_maxmass", 4000)
    SetInt("savegame.mod.combined.fyr_minmass", 2)

    -- Violence Section
    SetInt("savegame.mod.combined.VIOL_mode", 1)
    SetInt("savegame.mod.combined.VIOL_Chance", 1)
    SetInt("savegame.mod.combined.VIOL_mover", 2)
    SetInt("savegame.mod.combined.VIOL_turnr", 2)
    SetInt("savegame.mod.combined.VIOL_minmass", 5)
    SetInt("savegame.mod.combined.VIOL_maxmass", 2000)
    SetInt("savegame.mod.combined.VIOL_maxdist", 50)

    -- Joint Breakage Section
    SetInt("savegame.mod.combined.JOINT_Source", 1)
    SetInt("savegame.mod.combined.JOINT_Range", 5)
    SetInt("savegame.mod.combined.JOINT_Chance", 5)

    -- Damage Statistics Section
    SetInt("savegame.mod.combined.DAMSTAT_Currency", 1)

    -- Scanner defaults (always set on reset)
    SetFloat("savegame.mod.combined.scanner_cell", 1.0)
    SetInt("savegame.mod.combined.scanner_iter", 6)
    SetFloat("savegame.mod.combined.scanner_factor", 5.0)
    SetFloat("savegame.mod.combined.scanner_pad", 0.02)
    SetFloat("savegame.mod.combined.scanner_threshold", 0.9)
    SetBool("savegame.mod.combined.scanner_autobreak", false)
    SetFloat("savegame.mod.combined.scanner_cooldown", 8.0)
    SetBool("savegame.mod.combined.scanner_show_legend", true)
    SetBool("savegame.mod.combined.scanner_show_numbers", false)
    SetInt("savegame.mod.combined.scanner_max_breaks_per_tick", 3)
end
